name: CI

on: [push]

jobs:
    build:
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest]
            categort: [Redis, Postgres]
        runs-on: ${{ matrix.os }}

        steps:
        - uses: actions/checkout@v4

        - name: Setup .NET 8
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        - name: Build
          run: dotnet build src

        - name: Redis Tests
          run: dotnet test src --filter Name~${{ matrix.categort }}